[[redirects]]
  from = "/ph-events/*"
  to = "https://eu.i.posthog.com/:splat"
  status = 200
  force = true
  host = "eu.i.posthog.com"

[[redirects]]
  from = "/ph-static/*"
  to = "https://eu-assets.i.posthog.com/:splat"
  status = 200
  force = true
  host = "eu-assets.i.posthog.com"
